# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

steps:
  - shell: bash
    env:
      INSEE_APP_KEY: ${{ secrets.INSEE_APP_KEY }}
      INSEE_APP_SECRET: $${{ secrets.INSEE_APP_SECRET }}

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'